### ISSUE TITLE
Width problem on sidebar

### ISSUE THREAD

**Issue by rooferz** [tui2tone/flat-admin-bootstrap-templates#1]
Hello !
 
I met a problem during a visit on your live demo : 
I'm on my 9inches tab + Chrome browser and the sidebar doesn't fully appears on portrait mode.

Here is a screenshot
![screenshot_2015-11-09-22-22-12](https://cloud.githubusercontent.com/assets/4287777/11047150/529fa1f4-8731-11e5-8180-0c6a0dcf1e0d.png)

**Comment by rooferz** [comment]
I've got the same problem on a smartphone

**Comment by thearabbit** [comment]
I have the same problem.

**Comment by tui2tone** [comment]
Just fix it in v2.0.4
Thank you for report problem.
