### ISSUE TITLE
I would like change color scheme to `Depp Orange`?

### ISSUE THREAD

**Issue by thearabbit** [tui2tone/flat-admin-bootstrap-templates#10]
I would like change color scheme and any link (mouse over) to `Depp Orange = #ff6905`.
Please example me to change css.
Thanks for your helping

**Comment by tui2tone** [comment]
You can change simple by edit in  /dist/css/themes/flat-blue.css
duplicate file and replace `.flat-blue` class to `.flat-orange` or what you want.
change body class to new theme class.

then replace color in css file to orange
```html
.flat-orange a:hover {
    color: #09486b; 
}
```
to 
```html
.flat-orange a:hover {
    color: #ff6905; 
}
```

**Comment by thearabbit** [comment]
Thanks, look great
