### ISSUE TITLE
Why "flat-green.css" has class ".flat-blue" at line 633?

### ISSUE THREAD

**Issue by thearabbit** [tui2tone/flat-admin-bootstrap-templates#11]
In `flat-green.css` has `.flat-blue` class at line 633.
Why it is correct or not?

**Comment by tui2tone** [comment]
It's incorrect. I forgot to change.
Will fix it soon.
Thank you.

**Comment by thearabbit** [comment]
Waiting you...

**Comment by tui2tone** [comment]
Fix in v2.1.2
