### ISSUE TITLE
Excuse me, Button, Alert, Card  Color... should be change (-primary) for "-blue.css" vs "-green.css"?

### ISSUE THREAD

**Issue by thearabbit** [tui2tone/flat-admin-bootstrap-templates#12]
I seen that any `btn, alert, card ... ` don't change color when I change to `green`.
Should be change or not (-primary)
```js
Ex:
        <button type="submit" class="btn btn-primary">primary</button>
        <button type="submit" class="btn btn-success">success</button>
        <button type="submit" class="btn btn-info">info</button>
        <button type="submit" class="btn btn-warning">warning</button>
        <button type="submit" class="btn btn-danger">danger</button>
        <button type="reset" class="btn btn-default">default</button>
        <button type="reset" class="btn btn-link">link</button>
........................
```

**Comment by tui2tone** [comment]
Now theme only change navbar, sidebar , link color.
I think `*-primary` should not be change because it will be green like `*-success`.

I will review about this topic again.
Thank you.

**Comment by thearabbit** [comment]
Thanks for your reply, I would like to change color scheme to `#ff5722`.
So I think that should change any `btn, alert, card ....`?
