### ISSUE TITLE
Should be auto close sidebar (opening) when open other?

### ISSUE THREAD

**Issue by thearabbit** [tui2tone/flat-admin-bootstrap-templates#13]
I think that Should be auto close sidebar (opening) when open other?

**Comment by tui2tone** [comment]
What about open other? Please tell me example other that you open. I don't understand.

**Comment by thearabbit** [comment]
For example I click on `Form sidebar` and then I click  on `ui kid sidebar`. So the old sidebar (Form ) should be auto close /minimize when I open new.

**Comment by thearabbit** [comment]
Like sidebar of adminlte layout.

**Comment by tui2tone** [comment]
Fix in v2.1.2
