### ISSUE TITLE
Could I change them header color (navbar-....)?

### ISSUE THREAD

**Issue by thearabbit** [tui2tone/flat-admin-bootstrap-templates#2]
Could I change them header color?
```js
navbar-default
navbar-inverse
```

**Comment by tui2tone** [comment]
@thearabbit 
Current version not supported.
You can change color that you what in css file.
I will be implement in future version.
Thank you.

**Comment by thearabbit** [comment]
Thanks for your reply.

**Comment by tui2tone** [comment]
Added in v2.1.0
