### ISSUE TITLE
Last dropdown at Button samples

### ISSUE THREAD

**Issue by kaiqueg** [tui2tone/flat-admin-bootstrap-templates#26]
This is a known bug with bootstrap dropdown. You can see this happening [here]( http://tui2tone.github.io/flat-admin-bootstrap-templates/html/ui-kits/button.html). **Go to the last button and try it by yourself.**

The contents of the dropdown is not visible.

**Comment by daison12006013** [comment]
@kaiqueg, you should clarify your question, seems working fine on my side, on which issue on twbs/bootstrap is this? can you link?

on what browser? I'm using chrome and it seems working fine...

**Comment by kaiqueg** [comment]
Here's a video, I think it's better to understand.

I'm using Google Chrome v48.0.2564.103 m 64 bits
(it's inside a zip 'cause GitHub doesn't accept videos)
[2016-02-08-0141-00.zip](https://github.com/tui2tone/flat-admin-bootstrap-templates/files/121106/2016-02-08-0141-00.zip)
