### ISSUE TITLE
Problem with scrollup (refresh page)?

### ISSUE THREAD

**Issue by thearabbit** [tui2tone/flat-admin-bootstrap-templates#5]
I think that the `scrollup` at footer should be don't refresh page.
I use to use `http://markgoodyear.com/labs/scrollup/`, it is good.

**Comment by tui2tone** [comment]
Fix in v2.1.1
Thank you so much.

**Comment by thearabbit** [comment]
Thanks for your fix.
I think that `scrollup is popup` is good.
